name: tmdbtask
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.8
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1


flutter:


  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  background_image: "assets/images/splash_screen.jpg"
  android_12:
   background_image: "assets/images/splash_screen.jpg"
  android_screen_orientation: sensorPortrait
  fullscreen: true

